geonode/datarequests/urls.py
from django.conf.urls import patterns, url

from .views import ProfileRequestList, DataRequestList, DataRequestProfileList

urlpatterns = patterns(
    'geonode.datarequests.views',
    
    #url for landing page for profile and data requests
    url(r'^/?$','requests_landing',name='requests_landing'),
    url(r'^requests_csv/$','requests_csv',name='requests_csv'),
    url(r'^old_requests/$',DataRequestProfileList.as_view(),name='old_request_model_view'),
    
    #old requests
    url(r'^old_requests/$',DataRequestProfileList.as_view(),name='old_requests_model_view'),
    url(r'^old_requests/csv$','old_requests_csv',name='old_requests_csv'),
    url(r'^old_requests/(?P<pk>\d+)/$', 'old_request_detail', name="old_request_detail"),
    url(r'^old_requests/migrate/$','old_request_migration_all',name='old_request_migration_all'),
    url(r'^old_requests/(?P<pk>\d+)/migrate/$','old_request_migration', name='old_request_migration'),
    url(r'^old_requests/~count_facets/$','old_request_facet_count', name='old_request_facet_count'),
    
    #urls for registration
    url(r'^register/$','register',name='request_register'),
    url(r'^register/data_request/$', 'data_request_view', name='data_request_form'),
    url(r'^register/profile_request/$', 'profile_request_view', name='profile_request_form'),
    url(r'^register/verification-sent/$', 'email_verification_send', name='email_verification_send'),
    url(r'^register/email-verified/$', 'email_verification_confirm', name='email_verification_confirm'),

    #urls for profile requests
    url(r'^profile/$', ProfileRequestList.as_view(), name='profile_request_browse'),
    url(r'^profile_requests_csv/$', 'profile_requests_csv', name='profile_requests_csv'),
    
    url(r'^profile/(?P<pk>\d+)/$', 'profile_request_detail', name="profile_request_detail"),
    url(r'^profile/(?P<pk>\d+)/edit/$', 'profile_request_edit', name="profile_request_edit"),
    url(r'^profile/(?P<pk>\d+)/approve/$', 'profile_request_approve', name="profile_request_approve"),
    url(r'^profile/(?P<pk>\d+)/reject/$', 'profile_request_reject', name="profile_request_reject"),
    url(r'^prolfile/(?P<pk>\d+)/cancel/$', 'profile_request_cancel', name="profile_request_cancel"), 
    url(r'^profile/(?P<pk>\d+)/reconfirm/$', 'profile_request_reconfirm', name="profile_request_reconfirm"), 
    url(r'^prolfile/(?P<pk>\d+)/recreate_dir/$', 'profile_request_recreate_dir', name="profile_request_recreate_dir"), 
    url(r'^profile/~count_facets/$', 'profile_request_facet_count', name="profile_request_facet_count"),
    
    #urls for datarequests
    url(r'^data/$', DataRequestList.as_view(), name='data_request_browse'),
    url(r'^data/data_requests_csv/$', 'data_requests_csv', name='data_requests_csv'),
    url(r'^data/compute_size/$','data_request_compute_size_all', name='data_request_compute_size_all'),
    url(r'^data/reverse_geocode/$','data_request_reverse_geocode_all', name='data_request_reverse_geocode_all'),
    url(r'^data/tag_suc/$', 'data_request_tag_suc_all', name="data_request_tag_suc_all"), 
    
    url(r'^data/(?P<pk>\d+)/$', 'data_request_detail', name="data_request_detail"),
    url(r'^data/(?P<pk>\d+)/edit/$', 'data_request_edit', name="data_request_edit"),
    url(r'^data/(?P<pk>\d+)/approve/$', 'data_request_approve', name="data_request_approve"),
    url(r'^data/(?P<pk>\d+)/reject/$', 'data_request_reject', name="data_request_reject"),
    url(r'^data/(?P<pk>\d+)/cancel/$', 'data_request_cancel', name="data_request_cancel"),
    
    url(r'^data/(?P<pk>\d+)/compute_request_size/$', 'data_request_compute_size', name="data_request_compute_size"), 
    url(r'^data/(?P<pk>\d+)/tag_suc/$', 'data_request_tag_suc', name="data_request_tag_suc"), 
    url(r'^data/(?P<pk>\d+)/notify_suc/$', 'data_request_notify_suc', name="data_request_notify_suc"), 
    url(r'^data/(?P<pk>\d+)/notify_requester/$', 'data_request_notify_requester', name="data_request_notify_requester"), 
    url(r'^data/(?P<pk>\d+)/forward_request/$', 'data_request_forward_request', name="data_request_forward_request"), 
    url(r'^data/(?P<pk>\d+)/reverse_geocode/$', 'data_request_reverse_geocode', name="data_request_reverse_geocode"), 
    url(r'^data/assign_grid_refs/$','data_request_assign_gridrefs', name="data_request_assign_gridrefs"),
    
    url(r'^data/~count_facets/$', 'data_request_facet_count', name="data_request_facet_count"),

)

geonode/maptiles/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

import geonode.settings as settings

import views


urlpatterns = patterns('',
						url(r'^/?$', views.tiled_view, name='maptiles_main'),
                        url(r'^test/?$', views.tiled_view, { "overlay": settings.TILED_SHAPEFILE ,"test_mode":True} ),
                        url(r'^interest=(?P<interest>[^/]*)$', views.tiled_view, {"overlay": settings.TILED_SHAPEFILE_TEST}),
                        url(r'^addtocart/?$', views.process_georefs),
                        url(r'^validate/?$', views.georefs_validation),
                        url(r'^provinces/?$', views.province_lookup),
                        url(r'^provinces/(?P<province>[^/]*)$', views.province_lookup),
						url(r'^datasize/?$', views.georefs_datasize),
						url(r'^test2/?$', views.tiled_view2, { "overlay": settings.TILED_SHAPEFILE ,"test_mode":True} )
						)

geonode/people/maptiles/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

import geonode.settings as settings

import views


urlpatterns = patterns('',
						url(r'^/?$', views.tiled_view, name='maptiles_main'),
                        url(r'^test/?$', views.tiled_view, { "overlay": settings.TILED_SHAPEFILE_TEST ,"test_mode":True} ),
                        url(r'^interest=(?P<interest>[^/]*)$', views.tiled_view, {"overlay": settings.TILED_SHAPEFILE_TEST}),
                        url(r'^addtocart/?$', views.process_georefs),
                        url(r'^validate/?$', views.georefs_validation),
                        url(r'^provinces/?$', views.province_lookup),
                        url(r'^provinces/(?P<province>[^/]*)$', views.province_lookup),
						)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls
import geonode.cephgeo.urls

from geonode.api.urls import api

import django_cas_ng

import autocomplete_light
from geonode.views import forbidden

#from geonode import settings

# Setup Django Admin
autocomplete_light.autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

                       # Static pages
                       url(r'^/?$', 'geonode.views.philgrid', name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

                       # EULA URLs
                       url(r'^eula/', include('geonode.eula.urls'), name='eula'),

                       # Permission denied handler
                       url(r'^forbidden/$', forbidden, name='forbidden'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # data.json
                       url(r'^data.json$', 'geonode.catalogue.views.data_json', name='data_json'),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       #(r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),
                       url(r'^register/$','geonode.datarequests.views.register', name='register'),

                       # Accounts
                       #url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/login$', 'django_cas_ng.views.login', name='account_ajax_login'),
                       url(r'^account/login/$','django_cas_ng.views.login', name='account_login'),
                       url(r'^account/login/$', 'django_cas_ng.views.login', name='cas_ng_login'),
                       url(r'^account/logout/$', 'django_cas_ng.views.logout', name='cas_ng_logout'),
                       url(r'^account/logout/$', 'django_cas_ng.views.logout', name='account_logout'),
                       url(r'^accounts/callback$', 'django_cas_ng.views.callback', name='cas_ng_proxy_callback'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

		       #Geocoding
                       (r'^geocoding/',include('geonode.arealocate.urls',namespace='arealocate')),

                       # Data Request Profiles
                       (r'^requests/', include('geonode.datarequests.urls', namespace='datarequests')),

                       # Misc
                       # url(r'^captcha/', include('captcha.urls')),

					   # CephGeo
					   url(r'^ceph/', include("geonode.cephgeo.urls")),

             # Automation
             url(r'^automation/', include('geonode.automation.urls', namespace='automation')),

					   #MapTiles
					   url(r'^maptiles/',include("geonode.maptiles.urls")),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),
                       (r'^services/', include('geonode.services.urls')),
                       url(r'', include(api.urls)),
                       (r'^api/', include('geonode.api.urls')),

                       # Reports views
                       (r'^reports/', include('geonode.reports.urls')),
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

if 'notification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^notifications/', include('notification.urls')),
                            )

if 'simple_sso.sso_server' in settings.INSTALLED_APPS:
    from simple_sso.sso_server.server import Server
    server = Server()
    urlpatterns += server.get_urls()

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

# Featured Maps Pattens
urlpatterns += patterns('',
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/$', 'geonode.maps.views.featured_map'),
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/info$', 'geonode.maps.views.featured_map_info'),
                        )

geonode/maptiles/models.py
from django.db import models
from django_enumfield import enum

# Create your models here.
class SRS(enum.Enum):
    UTM51N = 32651
    PRS92 = 4683
    
    labels = {
        UTM51N: 'UTM 51N (Default)',
        PRS92: 'PRS 92',}
    
    EPSG_num = {
        'default' : 32651,
        'prs-92' : 4683,}

geonode/people/maptiles/models.py
from django.db import models

# Create your models here.

geonode/maptiles/templates/maptiles/maptiles_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} Data Tiles {% endblock %}


{% block body_outer %}
  {% block body %}
  {% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/maptiles/templates/maptiles/maptiles_leaflet_map.html
{% extends "layers/layer_leaflet_map.html" %}

geonode/maptiles/templates/maptiles/maptiles_map.html
{% extends "maptiles/maptiles_base.html" %} {% load i18n %} {% load dialogos_tags %} {% load agon_ratings_tags %} {% load bootstrap_tags %} {% load url from future %} {% load base_tags %} {% load guardian_tags %} {% block title %}Data Tiles Selection — {{ block.super }}{% endblock %} {% block head %}
<style>
.olImageLoadError {
    /* when OL encounters a 404, don't display the pink image */
    display: none !important;
}
div#site_wide_announcements {
    display: none;
}

body {
    overflow: hidden;
}


/*** custom checkboxes ***/

input[type=checkbox] {
    display: none;
}


/* to hide the checkbox itself */

input[type=checkbox] + label:before {
    font-family: FontAwesome;
    font-size: 16px;
    display: inline-block;
}

.label-dataclass {
    font-size: 16px;
}

input[type=checkbox] + label:before {
    content: "\f096";
}


/* unchecked icon */

input[type=checkbox] + label:before {
    letter-spacing: 20px;
}


/* space between checkbox and label */

input[type=checkbox]:checked + label:before {
    content: "\f046";
}


/* checked icon */

input[type=checkbox]:checked + label:before {
    letter-spacing: 20px;
}


/* allow space for check mark */

form table tr td {
    padding: 2px 1px;
}

div.side-navi-tab p {
    font-size: 12px;
    font-weight: 300;
}
</style>
{# {% if preview == 'geoext' %} #} {# {% include "maptiles/maptiles_explorer_map.html" %} #} {#{% else %} #} {#{% include "maptiles/maptiles_leaflet_map.html" %} #} {% include "maptiles/maptiles_geoext_map.html" %} {# {% endif %} #} {{ block.super }} {% endblock %} {% block body_class %}maptiles{% endblock %} {% block body_outer %} {% block body %}
<!--
<div class="page-header">
  <h2 class="page-title">Data Tiles</h2>
</div>
-->
<!--
<div class="row">
    <div class="col-md-9">
    <div id="embedded_map" class="mrg-btm">
-->
<div id="preview_map" style="margin-top:9px;"></div>
<div id="layerTree" style="margin-top:9px; position:fixed; top:100px;"></div>
<!--
    </div>
    </div>
-->
<!--
    <div class="col-md-3">
        <ul class="list-group">
     <li class="list-group-item">


                  </nobr>
           </li>
           <li class="list-group-item">

           </li>
           <li class="list-group-item">
               <div class="selections"><nav class="filter">
                   <h4><a href="{% url 'cephgeo.views.get_cart' %}" class="toggle toggle-nav"><i class="fa fa-shopping-cart"></i>Data Cart</a></h4>
                   <h4><a href="{% url 'cephgeo.views.ftp_request_list' %}" class="toggle toggle-nav"><i class="fa fa-database"></i>FTP Requests</a></h4>
                   </nav></div>
           </li>
        </ul>
    </div>
    -->
<!--
</div>
-->
<!--<ul class="list-group">
  </ul>-->
<br />
<div id="sideNavi">
    <div id="side-navi" class="side-navi-item item1">
        <div>Download Data</div>
    </div>
    <div class="side-navi-item item2">
        <div>Area Search</div>
    </div>
    <div class="side-navi-item item3">
        <div style="margin-top: -10px;">Bounding Box Selection</div>
    </div>
    <div class="side-navi-item item4">
        <div>FAQ</div>
    </div>
    <div class="side-navi-data">
        <div class="side-navi-tab">
            <div style="padding: 25px;">
                <h4 class="list-group-item-heading">{%trans "Download Data" %}</h4>
                <p>1. Select tiles on the left by either clicking on individual tiles, or select multiple tiles by holding down shift while drawing a bounding box.
                    <br><i>Note: You need to upload a shapefile of your area of interest before being able to select tiles for download. To upload a shapefile, please <a href="{% url 'datarequests:request_register' %}">update your data request.</a></i></p>
                <p>2. Select data type below and click Download.</p>
                <form name="georef_form" id="georef_form" action="/maptiles/addtocart/" method="POST">
                    {% csrf_token %}
                    <ul>
                        {% for class in data_classes %} {% if class != 'Unknown Type' %}
                        <li>
                            <input id="{{ class | slugify }}" name="{{ class | slugify }}" type="checkbox" />
                            <label class="label-dataclass" for="{{ class | slugify }}">{{ class }}</label>
                        </li>
                        {% endif %} {% endfor %}
                    </ul>
                    <input type="text" id="georef_area" name="georef_area" style="display:none" />
                      {% if jurisdiction_yes %} {% else %} <div onclick="alert('Request New Data with an Area of Interest Shapefile to be able to use the Data Tiles feature.\nFor any inquiries, email us at lipad@dream.upd.edu.ph')" /> {% endif %}
                    <input type="submit" id="georef_submit" name="georef_submit" value="Submit" class="btn btn-default"
                      {% if jurisdiction_yes %} /> {% else %} style="opacity:0.65" disabled/> </div>{% endif %}
                </form>
            </div>
        </div>
        <div class="side-navi-tab">
            <div>
                <h4 class="list-group-item-heading">{%trans "Area Search" %}</h4>
                <p>
                    Type in location to zoom into it.
                </p>
                <form name='geocode_form' id="geocode_form">
                    {% csrf_token %}
                    <input type="text" id="geocode_input" name="geocode_input" />
                </form>
                <br />
                <a id="geocode_submit" name="geocode_submit" class="btn btn-default">Search</a>
            </div>
        </div>
        <div class="side-navi-tab">
            <div>
                <h4 class="list-group-item-heading">{%trans "Bounding Box Selection" %}</h4>
                <p>
                    Select a dataset according to its location. Use WGS 1984 or EPSG:4326 in decimal degrees.
                </p>
                <form id="bbox_form">
                    <table>
                        <tr>
                            <td>Upper Lat (&deg;N) limit: </td>
                            <td>
                                <input type="number" id="upperlimit" name="upperlimit" value=0 step="any" />
                            </td>
                        </tr>
                        <tr>
                            <td>Left Lng (&deg;E) limit: </td>
                            <td>
                                <input type="number" id="leftlimit" name="leftlimit" value=0 step="any" />
                            </td>
                        </tr>
                        <tr>
                            <td>Right Lng (&deg;E) limit: </td>
                            <td>
                                <input type="number" id="rightlimit" name="rightlimit" value=0 step="any" />
                            </td>
                        </tr>
                        <tr>
                            <td>Lower Lat (&deg;N) limit: </td>
                            <td>
                                <input type="number" id="lowerlimit" name="lowerlimit" value=0 step="any" />
                            </td>
                        </tr>
                    </table>
                    <br />
                    <input type="submit" id="bbox_submit" name="bbox_submit" value="Submit Bounding Box" class="btn btn-default" />
                </form>
            </div>
        </div>
        <div class="side-navi-tab">
            <div>
                <h4 class="list-group-item-heading">{%trans "General Information" %}</h4>
                <p>
                    All digital elevation models were acquired and processed by the UP Training Center for Applied Geodesy and Photogrammetry (UP-TCAGP), through the DOST-GIA funded Disaster Risk and Exposure Assessment for Mitigation (DREAM) Program.
                </p>
                <p>
                    The Digital Terrain Models (DTM) and Digital Surface Models (DSM) were acquired by an Optech ALTM Pegasus LiDAR system.
                </p>
                <p>
                    All digital elevation models, point cloud and orthophotographs were acquired and processed by the DREAM/PHIL-LiDAR 1 Program.
                </p>
                <p>
                    All rights reserved 2013-2017
                </p>
            </div>
        </div>
    </div>
</div>
<div style="position: fixed; top: 99px; left: 50px;">
    <div id="floating-legend" class="floating-tab" style="background: white; padding: 0px 50px 15px 15px; width: auto; height: 200px; display: inline-block; top: 114px;">
        <h4 class="list-group-item-heading">Legend</h4>
        <div class="legend-radio-buttons" style="display: block; float: left;">
            <div>
                <label class="form-check-label">
                    <input class="form-check-input" type="radio" name="sld" value="dtm" onclick="changeSLD()">
                </label>
            </div>
            <div>
                <label class="form-check-label">
                    <input class="form-check-input" type="radio" name="sld" value="dsm" onclick="changeSLD()">
                </label>
            </div>
            <div>
                <label class="form-check-label">
                    <input class="form-check-input" type="radio" name="sld" value="ortho" onclick="changeSLD()">
                </label>
            </div>
            <div>
                <label class="form-check-label">
                    <input class="form-check-input" type="radio" name="sld" value="laz" onclick="changeSLD()">
                </label>
            </div>
            <div>
                <label class="form-check-label">
                    <input class="form-check-input" type="radio" name="sld" value="clear" onclick="changeSLD()">
                </label>
            </div>
            <div>
                <label class="form-check-label">
                    <input class="form-check-input" type="radio" name="sld" value="all" onclick="changeSLD()" checked>
                </label>
            </div>

        </div>
        <div class="legend-images" style="display: block; float: left; position: relative;">
            <img id="dtm_icon" src="{{ dtm_lgd }}">
            <img id="dsm_icon" style="position: absolute; top: 25px; left: 0px;" src="{{ dsm_lgd }}">
            <img id="ortho_icon" style="position: relative; top: 50px; left: -50px;" src="{{ ortho_lgd }}">
            <img id="laz_icon" style="position: absolute; top: 75px; left: 0px;" src="{{ laz_lgd }}">
            <p style="position: absolute; top: 98px; left: 2px;">C L E A R</p>
            <p style="position: absolute; top: 123px; left: 2px;">A L L</p>
            <img style="position: absolute; top: 150px; left: 0px;" id="legend_icon2" src="{{jurisdiction.resource.get_legend.url}}">
        </div>
    </div>
    <!-- <img id="legend_icon" src="{{ grid.resource.get_legend.url }}"><br/> -->
    <div class="floating-tab" style="min-height: 150px; background: white; padding: 15px 15px; margin-top: 20px; width: 300px;">
        <div id="notif" style="margin: 0px -15px;">
        </div>
        <div style="max-height: 500px; overflow-y: auto; overflow-x: hidden;">
            <div class="page-header" style="margin-top: -10px;">
                <h4 class="page-title">Selected Tiles <div id="data_size_display" style="display:inline-block;">- 0 Byte</div></h3>
       </div>
       <div>
         <input id="checkbox_all" type="checkbox" onClick="toggle_all_checkboxes(this)" style="display:inline-block;">
         <button onclick="delete_checked()"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
       </div>
       <div class="row" id="point_display" style="padding:0px 30px 30px 30px;">
       </div>
    </div>
  </div>
</div>
 <!--ATTRIBUTION-->
 <!-- replaced with local OSM layergroup -->
<div style="position: fixed; bottom: 50px; left: 50px; width: 220px; white-space: normal;">
  <!--  <a href='http://giscience.uni-hd.de/'>GIScience Research Group @ University of Heidelberg</a> &mdash;<br>
   Map data &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a> -->
    LiPAD uses basemaps from OSM. &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>
</div>
{% endblock %}
{% endblock %}
{% block extra_script %}
<script type="text/javascript">
    {% autoescape off %}
    submit_location = function(e){
            form = new FormData($("#geocode_form")[0]);
            $.ajax({
               type: "POST",
               url: "/geocoding/",
               data: form, //form.serialize(), // serializes the form's elements.
               contentType: false,
               processData: false,
               success: function(data)
               {
                   console.log(data);
                   zoomOnBbox(data.bbox);
                },
                error: function(data){
        console.log(data);
                    alert("Invalid area");
                }
            });
            return false;
    }

    $(document).ready( function() {
      SideNavi.init('right', {
        container : '#sideNavi',
        item : '.side-navi-item',
        data : '.side-navi-data',
        tab : '.side-navi-tab',
        active : '.active'
      });
      document.getElementById("side-navi").click();

         $('#geocode_form').submit(function (e){
            return false;
         });
         $('#geocode_input').bind("enterKey", function(e){});
         $('#geocode_input').keyup(function(e){
            if(e.keyCode == 13){
                submit_location(e);
                return false;
            }
         });
         $("#geocode_submit").click(submit_location);
    });
    window.addEventListener("keydown", function(e) {
      // space and arrow keys
      if([32, 37, 38, 39, 40].indexOf(e.keyCode) > -1) {
          e.preventDefault();
      }
}, false);
    {% endautoescape %}
</script>
{% endblock %}

geonode/maptiles/templates/maptiles/maptiles_map_form.html
{% extends "ceph_base.html" %}
{% load i18n %}
{% load url from future %}
{% block title %} {% trans "Data Input Form" %} - {{ block.super }} {% endblock %}

{% block body_class %}Cephgeo Data Input{% endblock %}

{% block body_outer %}
  {% block body %}
  
  <div class="page-header">
    <h2 class="page-title">{% trans "Georef Input Form" %}</h2>
  </div>
  
  <form method="POST"  id="georef_form" name="georef_form" >
     {% csrf_token %}
    <input type="textarea" name="georef_area" ></input>
    <input id="georef_submit" type="submit" name="georef_submit" value="Submit"></input>
</form>
  
{% endblock body %}
 {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}