geonode/datarequests/urls.py
from django.conf.urls import patterns, url

from .views import ProfileRequestList, DataRequestList, DataRequestProfileList

urlpatterns = patterns(
    'geonode.datarequests.views',
    
    #url for landing page for profile and data requests
    url(r'^/?$','requests_landing',name='requests_landing'),
    url(r'^requests_csv/$','requests_csv',name='requests_csv'),
    url(r'^old_requests/$',DataRequestProfileList.as_view(),name='old_request_model_view'),
    
    #old requests
    url(r'^old_requests/$',DataRequestProfileList.as_view(),name='old_requests_model_view'),
    url(r'^old_requests/csv$','old_requests_csv',name='old_requests_csv'),
    url(r'^old_requests/(?P<pk>\d+)/$', 'old_request_detail', name="old_request_detail"),
    url(r'^old_requests/migrate/$','old_request_migration_all',name='old_request_migration_all'),
    url(r'^old_requests/(?P<pk>\d+)/migrate/$','old_request_migration', name='old_request_migration'),
    url(r'^old_requests/~count_facets/$','old_request_facet_count', name='old_request_facet_count'),
    
    #urls for registration
    url(r'^register/$','register',name='request_register'),
    url(r'^register/data_request/$', 'data_request_view', name='data_request_form'),
    url(r'^register/profile_request/$', 'profile_request_view', name='profile_request_form'),
    url(r'^register/verification-sent/$', 'email_verification_send', name='email_verification_send'),
    url(r'^register/email-verified/$', 'email_verification_confirm', name='email_verification_confirm'),

    #urls for profile requests
    url(r'^profile/$', ProfileRequestList.as_view(), name='profile_request_browse'),
    url(r'^profile_requests_csv/$', 'profile_requests_csv', name='profile_requests_csv'),
    
    url(r'^profile/(?P<pk>\d+)/$', 'profile_request_detail', name="profile_request_detail"),
    url(r'^profile/(?P<pk>\d+)/edit/$', 'profile_request_edit', name="profile_request_edit"),
    url(r'^profile/(?P<pk>\d+)/approve/$', 'profile_request_approve', name="profile_request_approve"),
    url(r'^profile/(?P<pk>\d+)/reject/$', 'profile_request_reject', name="profile_request_reject"),
    url(r'^prolfile/(?P<pk>\d+)/cancel/$', 'profile_request_cancel', name="profile_request_cancel"), 
    url(r'^profile/(?P<pk>\d+)/reconfirm/$', 'profile_request_reconfirm', name="profile_request_reconfirm"), 
    url(r'^prolfile/(?P<pk>\d+)/recreate_dir/$', 'profile_request_recreate_dir', name="profile_request_recreate_dir"), 
    url(r'^profile/~count_facets/$', 'profile_request_facet_count', name="profile_request_facet_count"),
    
    #urls for datarequests
    url(r'^data/$', DataRequestList.as_view(), name='data_request_browse'),
    url(r'^data/data_requests_csv/$', 'data_requests_csv', name='data_requests_csv'),
    url(r'^data/compute_size/$','data_request_compute_size_all', name='data_request_compute_size_all'),
    url(r'^data/reverse_geocode/$','data_request_reverse_geocode_all', name='data_request_reverse_geocode_all'),
    url(r'^data/tag_suc/$', 'data_request_tag_suc_all', name="data_request_tag_suc_all"), 
    
    url(r'^data/(?P<pk>\d+)/$', 'data_request_detail', name="data_request_detail"),
    url(r'^data/(?P<pk>\d+)/edit/$', 'data_request_edit', name="data_request_edit"),
    url(r'^data/(?P<pk>\d+)/approve/$', 'data_request_approve', name="data_request_approve"),
    url(r'^data/(?P<pk>\d+)/reject/$', 'data_request_reject', name="data_request_reject"),
    url(r'^data/(?P<pk>\d+)/cancel/$', 'data_request_cancel', name="data_request_cancel"),
    
    url(r'^data/(?P<pk>\d+)/compute_request_size/$', 'data_request_compute_size', name="data_request_compute_size"), 
    url(r'^data/(?P<pk>\d+)/tag_suc/$', 'data_request_tag_suc', name="data_request_tag_suc"), 
    url(r'^data/(?P<pk>\d+)/notify_suc/$', 'data_request_notify_suc', name="data_request_notify_suc"), 
    url(r'^data/(?P<pk>\d+)/notify_requester/$', 'data_request_notify_requester', name="data_request_notify_requester"), 
    url(r'^data/(?P<pk>\d+)/forward_request/$', 'data_request_forward_request', name="data_request_forward_request"), 
    url(r'^data/(?P<pk>\d+)/reverse_geocode/$', 'data_request_reverse_geocode', name="data_request_reverse_geocode"), 
    url(r'^data/assign_grid_refs/$','data_request_assign_gridrefs', name="data_request_assign_gridrefs"),
    
    url(r'^data/~count_facets/$', 'data_request_facet_count', name="data_request_facet_count"),

)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls
import geonode.cephgeo.urls

from geonode.api.urls import api

import django_cas_ng

import autocomplete_light
from geonode.views import forbidden

#from geonode import settings

# Setup Django Admin
autocomplete_light.autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

                       # Static pages
                       url(r'^/?$', 'geonode.views.philgrid', name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

                       # EULA URLs
                       url(r'^eula/', include('geonode.eula.urls'), name='eula'),

                       # Permission denied handler
                       url(r'^forbidden/$', forbidden, name='forbidden'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # data.json
                       url(r'^data.json$', 'geonode.catalogue.views.data_json', name='data_json'),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       #(r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),
                       url(r'^register/$','geonode.datarequests.views.register', name='register'),

                       # Accounts
                       #url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/login$', 'django_cas_ng.views.login', name='account_ajax_login'),
                       url(r'^account/login/$','django_cas_ng.views.login', name='account_login'),
                       url(r'^account/login/$', 'django_cas_ng.views.login', name='cas_ng_login'),
                       url(r'^account/logout/$', 'django_cas_ng.views.logout', name='cas_ng_logout'),
                       url(r'^account/logout/$', 'django_cas_ng.views.logout', name='account_logout'),
                       url(r'^accounts/callback$', 'django_cas_ng.views.callback', name='cas_ng_proxy_callback'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

		       #Geocoding
                       (r'^geocoding/',include('geonode.arealocate.urls',namespace='arealocate')),

                       # Data Request Profiles
                       (r'^requests/', include('geonode.datarequests.urls', namespace='datarequests')),

                       # Misc
                       # url(r'^captcha/', include('captcha.urls')),

					   # CephGeo
					   url(r'^ceph/', include("geonode.cephgeo.urls")),

             # Automation
             url(r'^automation/', include('geonode.automation.urls', namespace='automation')),

					   #MapTiles
					   url(r'^maptiles/',include("geonode.maptiles.urls")),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),
                       (r'^services/', include('geonode.services.urls')),
                       url(r'', include(api.urls)),
                       (r'^api/', include('geonode.api.urls')),

                       # Reports views
                       (r'^reports/', include('geonode.reports.urls')),
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

if 'notification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^notifications/', include('notification.urls')),
                            )

if 'simple_sso.sso_server' in settings.INSTALLED_APPS:
    from simple_sso.sso_server.server import Server
    server = Server()
    urlpatterns += server.get_urls()

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

# Featured Maps Pattens
urlpatterns += patterns('',
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/$', 'geonode.maps.views.featured_map'),
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/info$', 'geonode.maps.views.featured_map_info'),
                        )

geonode/datarequests/models/base_request.py
from django.db import models
from django.conf import settings
from django.contrib.sites.models import Site
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils import dateformat
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext as _
from django.utils.encoding import iri_to_uri
from django.utils.http import urlquote
from django_enumfield import enum
from django.core import validators
from django_auth_ldap.backend import LDAPBackend, ldap_error

from model_utils import Choices
from model_utils.models import TimeStampedModel, StatusModel

from geonode.cephgeo.models import UserJurisdiction
from geonode.datarequests.utils import create_login_credentials, create_ad_account, add_to_ad_group
from geonode.documents.models import Document
from geonode.layers.models import Layer
from geonode.people.models import OrganizationType, Profile

from pprint import pprint
from unidecode import unidecode

import traceback

from django.conf import settings as local_settings


class LipadOrgType(models.Model):
    val = models.CharField(_('Value'), max_length=100)
    display_val = models.CharField(_('Display'), max_length=100)
    category = models.CharField(_('Sub'), max_length=100, null=True)

    class Meta:
        app_label = "datarequests"

    def __unicode__(self):
        return (_('{}').format(self.val,))

class BaseRequest(TimeStampedModel):
    
    STATUS = Choices(
        ('pending', _('Pending')),
        ('approved', _('Approved')),
        ('cancelled', _('Cancelled')),
        ('rejected', _('Rejected')),
        ('unconfirmed',_('Unconfirmed Email')),
    )

    profile = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    administrator = models.ForeignKey(
        Profile,
        null=True,
        blank=True,
        related_name="admin+"
    )

    rejection_reason = models.CharField(
        _('Reason for Rejection'),
        blank=True,
        null=True,
        max_length=100,
    )

    additional_remarks = models.TextField(
        blank = True,
        null = True,
        help_text= _('Additional remarks by an administrator'),
    )

    additional_rejection_reason = models.TextField(
        _('Additional details about rejection'),
        blank=True,
        null=True,
        )

    class Meta:
        abstract = True
        app_label = "datarequests"

class RequestRejectionReason(models.Model):
    reason = models.CharField(_('Reason for rejection'), max_length=100)

    class Meta:
        app_label = "datarequests"

    def __unicode__(self):
        return (_('{}').format(self.reason,))

geonode/datarequests/models/email_msg_templates.py
VERIFICATION_EMAIL_TEXT="""
     Dear <strong>{}</strong>,

    Please paste the following URL in your browser to verify your email and complete your Data Request Registration.
    {}

    For inquiries, you can contact us as at {}.

    Regards,
    LiPAD Team
     """
     
VERIFICATION_EMAIL_HTML= """
    <p>Dear <strong>{}</strong>,</p>

   <p>Please click on the following link to verify your email and complete your Data Request Registration.</p>
   <p><a rel="nofollow" target="_blank" href="{}">{}</a></p>
   <p>For inquiries, you can contact us as at <a href="mailto:{}" target="_top">{}</a></p>
   </br>
    <p>Regards,</p>
    <p>LiPAD Team</p>
    """

geonode/datarequests/models/suc_directory.py
from django.db import models
from django.conf import settings
from django.contrib.sites.models import Site
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils import dateformat
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext as _
from django.utils.encoding import iri_to_uri
from django.utils.http import urlquote
from django_enumfield import enum
from django.core import validators

class SUC_Contact(models.Model):
    institution_abrv = models.CharField(_('Institution Name(abbrev.)'), max_length=50, null=False, blank = False )
    institution_full = models.CharField(_('Institution Name(full)'), max_length=100, null=False, blank = False )
    name = models.CharField(_('Full name of contact person'),max_length = 100)
    position = models.CharField(_('Position'),max_length = 50)
    email_address = models.EmailField(_('Email Address'))
    salutation = models.CharField(_('Salutation (optional)'), max_length = 10, blank=True, null = True)
    username = models.CharField(_('Username associated with this SUC contact'), max_length=50, null=False, blank=False)   
    
    class Meta:
        app_label = "datarequests"
        verbose_name = "SUC Contact"
    
    def __unicode__(self):
        s = ""
        
        if self.salutation:
            s += self.salutation
            
        s += "{0}, {1} for {2}".format(self.name, self.position, self.institution_full)
        
        return s
    

geonode/datarequests/templates/datarequests/_data_request_content.html
{% load i18n %}
<div class="row">
  <div class="col-md-3">
    <div class="selections">
      <h5>
        {% trans "Filters" %}
        <a href="." id="clear-search" class="pull-right">{% trans "Clear all filters" %}</a>
      </h5>
      </div>
        {% include "search/_text_filter.html" %}
      <div id="slide-pane">
        {% include "datarequests/_data_request_filters.html" %}
      </div>
  </div>
  <div class="col-md-9">
    <div class="col-md-3">
      <span>Total: </span>
      <span ng-bind="total_counts"></span>
    </div>
    {% include "datarequests/_requests_sort_filters.html" %}
    <div class="col-md-12 grid-spacer">
    {% include 'datarequests/_data_request_list_item.html' %}
    {% include 'search/_pagination.html' %}
    </div>
  </div>
</div>

geonode/datarequests/templates/datarequests/_old_requests_content.html
{% load i18n %}
<div class="row">
  <div class="col-md-3">
    <div class="selections">
      <h5>
        {% trans "Filters" %}
        <a href="." id="clear-search" class="pull-right">{% trans "Clear all filters" %}</a>
      </h5>
      </div>
        {% include "search/_text_filter.html" %}
      <div id="slide-pane">
        {% include "datarequests/_old_requests_filters.html" %}
      </div>
  </div>
  <div class="col-md-9">
    <div class="col-md-3">
      <span>Total: </span>
      <span ng-bind="total_counts"></span>
    </div>
    {% include "datarequests/_requests_sort_filters.html" %}
    <div class="col-md-12 grid-spacer">
    {% include 'datarequests/old_requests_model_list_item.html' %}
    {% include 'search/_pagination.html' %}
    </div>
  </div>
</div>

geonode/datarequests/templates/datarequests/_profile_request_content.html
{% load i18n %}
<div class="row">
  <div class="col-md-3">
    <div class="selections">
      <h5>
        {% trans "Filters" %}
        <a href="." id="clear-search" class="pull-right">{% trans "Clear all filters" %}</a>
      </h5>
      </div>
        {% include "search/_text_filter.html" %}
      <div id="slide-pane">
        {% include "datarequests/_profile_request_filters.html" %}
      </div>
  </div>
  <div class="col-md-9">
    <div class="col-md-3">
      <span>Total: </span>
      <span ng-bind="total_counts"></span>
    </div>
    {% include "datarequests/_requests_sort_filters.html" %}
    <div class="col-md-12 grid-spacer">
    {% include 'datarequests/_profile_request_list_item.html' %}
    {% include 'search/_pagination.html' %}
    </div>
  </div>
</div>

geonode/datarequests/templates/datarequests/_requests_sort_filters.html
{% load i18n %}

<div class="col-md-6">
  <ul class="list-inline pull-left" id="sort">
    <li><a data-value="-date" data-filter="order_by" class="selected" ng-click="single_choice_listener($event)">{% trans "Most recent" %}</a></li>
    <li><a data-value="date" data-filter="order_by" ng-click="single_choice_listener($event)">{% trans "Less recent" %}</a></li>
  </ul>
</div>

geonode/datarequests/templates/datarequests/data_detail_edit.html
{% extends "layers/layer_base.html" %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load crispy_forms_tags %}
{% load bootstrap_tags %}
{% load url from future %}
{% load base_tags %}
{% load guardian_tags %}
{% load eula_extras %}

{% block title %}{% trans "Data Request Details Edit" %} — {{ block.super }}{% endblock %}

{% block head %}
{{ block.super }}
{% endblock %}

{% block body_class %}{% trans "Data Request" %}{% endblock %}

{% block body_outer %}
<div class="page-header">
  <a href="{% url 'datarequests:data_request_browse' %}" class="btn btn-primary pull-right">{% trans "View All Requests" %}</a>
  <h2 class="page-title">{% trans "Data Request Details" %}</h2>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-1">

    <form id="edit-form" action='{% url "datarequests:data_request_edit" pk=data_request.pk %}' class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}

          <div class="form-controls">
            {% crispy form %}
          </div>
          <div class="form-actions">
            <input type="submit" class="btn btn-primary btn-md" id="form-submit" name ="form-submit" value="{% trans 'Save' %}"/>
            <a href='{% url "datarequests:data_request_detail" pk=data_request.pk %}' class="btn btn-default" >{% trans "Cancel Editing" %}</a>
          </div>

      </form>

  </div>

  <div class="col-md-4">

    <ul class="list-group">
      <li class="list-group-item">
        <h5 class="list-group-item-heading">{%trans "Data Request Status" %}</h5>

        <div class="row data-request-status-parent">
          {% if data_request.status == 'pending' %}
            <div class="col-sm-12 data-request-status label pending-request">
          {% elif data_request.status == 'approved' %}
            <div class="col-sm-12 label data-request-status label-success">
          {% else %}
            <div class="col-sm-12 label data-request-status label-danger">
          {% endif %}
              <strong>{{ data_request.get_status_display }}</strong>
            </div>
        </div>

        {% if data_request.status == 'rejected' or data_request.status == 'cancelled' %}
          <p><strong>{% trans "Reason" %}</strong>: {{ data_request.rejection_reason }}</p>
          {% if data_request.additional_rejection_reason %}
              <p><strong>{% trans "Additional Details" %}</strong>: {{ data_request.additional_rejection_reason }}</p>
          {% endif %}
        {% endif %}
      </li>
  </ul>
  <input type="hidden" id="data_request_id" value="{{data_request.pk}}"></input>
  </div> <!-- col-md-4 -->
</div> <!-- row -->
{% endblock %}

{% block extra_script %}

      {% load i18n %}
      <script src="{{ STATIC_URL }}geonode/js/datarequests/registration2.js"></script>
        <script>
    $('#form-submit').click(function(e){
        e.preventDefault();
        $('#edit-form').submit();
        });
        </script>
      
{% endblock extra_script %}

geonode/datarequests/templates/datarequests/profile_detail_edit.html
{% extends "layers/layer_base.html" %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load crispy_forms_tags %}
{% load bootstrap_tags %}
{% load url from future %}
{% load base_tags %}
{% load guardian_tags %}
{% load eula_extras %}

{% block title %}{% trans "Profile Request Details" %} — {{ block.super }}{% endblock %}

{% block head %}
{% if resource %}
    {% if preview == 'geoext' %}
      {% include "layers/layer_geoext_map.html" %}
    {% else %}
      {% include "layers/layer_leaflet_map.html" %}
    {% endif %}
{% endif %}
{{ block.super }}
{% endblock %}

{% block body_class %}{% trans "Profile Request" %}{% endblock %}

{% block body_outer %}
<div class="page-header">
  <a href="{% url 'datarequests:profile_request_browse' %}" class="btn btn-primary pull-right">{% trans "View All Requests" %}</a>
  <h2 class="page-title">{% trans "Profile Request Details" %}</h2>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-1">

    <form id="edit-form" action='{% url "datarequests:profile_request_edit" pk=profile_request.pk %}' class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}

          <div class="form-controls">
            {% crispy form %}
          </div>
          <div class="form-actions">
            <input type="submit" class="btn btn-primary btn-md" id="form-submit" name ="form-submit" value="{% trans 'Save' %}"/>
            <a href='{% url "datarequests:profile_request_detail" pk=profile_request.pk %}' class="btn btn-default" >{% trans "Cancel Editing" %}</a>
          </div>

      </form>

  </div>

  <div class="col-md-4">

    <ul class="list-group">
      <li class="list-group-item">
        <h5 class="list-group-item-heading">{%trans "Data Request Status" %}</h5>

        <div class="row data-request-status-parent">
          {% if profile_request.status == 'pending' %}
            <div class="col-sm-12 data-request-status label pending-request">
          {% elif profile_request.status == 'approved' %}
            <div class="col-sm-12 label data-request-status label-success">
          {% else %}
            <div class="col-sm-12 label data-request-status label-danger">
          {% endif %}
              <strong>{{ profile_request.get_status_display }}</strong>
            </div>
        </div>

        {% if profile_request.status == 'rejected' or profile_request.status == 'cancelled' %}
          <p><strong>{% trans "Reason" %}</strong>: {{ profile_request.rejection_reason }}</p>
          {% if profile_request.additional_rejection_reason %}
              <p><strong>{% trans "Additional Details" %}</strong>: {{ profile_request.additional_rejection_reason }}</p>
          {% endif %}
        {% endif %}
      </li>
  </ul>
  <input type="hidden" id="profile_request_id" value="{{profile_request.pk}}"></input>
  </div> <!-- col-md-4 -->
</div> <!-- row -->
{% endblock %}

{% block extra_script %}

    {% if GEOGIG_ENABLED and resource.link_set.geogig %}
        {% with "_geogig_scripts.html" as geogig_scripts_template %}
            {% include  geogig_scripts_template %}
        {% endwith %}
    {% endif %}
    <script type="text/javascript">
      // $('#layer').css('opacity', 0);
      // $('#layer').css('visibility', 'hidden');
      // $('.nav-tabs').on('click', 'a[href="#layer"]', function() {
      //   $('#layer').css('opacity', 1);
      //   $('#layer').css('visibility', 'visible');

      // });
      {% if resource.get_legend.link_type == 'json' %}
      $.getJSON('{{resource.get_legend_url}}', function (data) {
          var legend = data.layers[0].legend;
          var items = [];
          $.each(legend, function (key, dvalue) {
              items.push('<li><img src="data:image/png;base64,' + dvalue.imageData + '">'+dvalue.label+'</li>');
          });

          $('<ul/>', {
              'class': 'arcgis-legend',
              html: items.join('')

          }).appendTo('#legend_placeholder');

      });
      {% endif %}
    </script>

      {% load i18n %}
      <script src="{{ STATIC_URL }}geonode/js/datarequests/registration.js"></script>
        <script>
    $('#form-submit').click(function(e){
        e.preventDefault();
        $('#edit-form').submit();
        });
        </script>
      
{% endblock extra_script %}

geonode/datarequests/templates/datarequests/requests_landing.html
{% extends "site_base.html" %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load bootstrap_tags %}
{% load url from future %}
{% load base_tags %}
{% load guardian_tags %}
{% load eula_extras %}

{% block title %}{% trans "LiPAD Requests" %} - {{block.super}}{% endblock %}

{% block body_class %}{% trans "LiPAD Requests Landing Page for Administrators" %}{% endblock %}


{% block body_outer %}
<div class="page-header">
    <h2 class="page-title">{% trans "Submitted LiPAD Requests" %}</h2>
</div>
<div>
<a href={% url 'datarequests:profile_request_browse' %} class="btn btn-primary ">Profile Requests</a>
<a href={% url 'datarequests:data_request_browse' %} class="btn btn-primary">Data Requests</a>
<a href={% url 'datarequests:requests_csv' %} class="btn btn-primary">Download Requests CSV</a>
</div>
<br /><br />
<div>
<a href={% url 'datarequests:old_requests_model_view' %} class="btn btn-primary">Old Requests List</a>
<a href={% url 'datarequests:old_request_migration_all' %} class="btn btn-primary">Migrate Old Requests To New Models</a>
</div>
{% endblock %}