geonode/automation/urls.py
from django.conf.urls import url, patterns, include
import views

urlpatterns = patterns('',
                       url(r'^input/$', views.metadata_job,
                           name='metadata_job'),
                       url(r'^/', include('geonode.cephgeo.urls')),
                       )

geonode/cephgeo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, user_passes_test

import views

urlpatterns = patterns('',
                       url(r'^$', login_required(TemplateView.as_view(template_name='ceph_main.html')),
                           name='ceph_main'),
                       url(r'^error/$', views.error),
                       url(r'^json_list/(?P<sort>[A-Za-z]+)/$',
                           views.file_list_json),
                       url(r'^json_list/(?P<sort>[A-Za-z]+)/(?P<grid_ref>[A-Za-z0-9]+)/$',
                           views.file_list_json),
                       url(r'^cart/$', views.get_cart, ),
                       url(r'^cart_clear/$', views.clear_cart, ),
                       url(r'^cart_json/$', views.get_cart_json, ),
                       url(r'^geotypes/$', views.get_obj_ids_json, ),
                       url(r'^ftp/$', views.create_ftp_folder, ),
                       url(r'^ftp/(?P<projection>[A-Za-z0-9\-]+)/$',
                           views.create_ftp_folder, ),
                       url(r'^ftprequests/$', views.ftp_request_list, ),
                       url(r'^ftprequests/(?P<sort>[A-Za-z]+)/$',
                           views.ftp_request_list, ),
                       url(
                           r'^ftprequests/r=(?P<ftp_req_name>ftprequest_[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{4})/$', views.ftp_request_details),
                       url(r'tilecheck/', views.tile_check),
                       # Data Management Views
                       url(r'^datamanager/$', views.management,
                           name='data_management'),
                       url(r'^datamanager/input/$',
                           views.data_input, name='data_input'),
                       url(r'^datamanager/remove_ceph_objects/$',
                           views.data_remove, name='data_remove'),
                       url(r'^datamanager/update_lidar_coverage/$',
                           views.update_lidar_coverage, name='update_lidar_coverage'),
                       url(r'^datamanager/update_fhm_metadata/$',
                           views.update_fhm_metadata, name='update_fhm_metadata'),
                       url(r'^datamanager/update_pl2_metadata/$',
                           views.update_pl2_metadata, name='update_pl2_metadata'),
                       url(r'^datamanager/update_sar_metadata/$',
                           views.update_sar_metadata, name='update_sar_metadata'),
                       url(r'^datamanager/floodplain_keywords/$',
                           views.update_floodplain_keywords, name='update_floodplain_keywords'),
                       url(r'^datamanager/seed_fhm_layers/$',
                           views.seed_fhm_layers, name='seed_fhm_layers'),
                       url(r'^datamanager/seed_resource_layers/$',
                           views.seed_resource_layers, name='seed_resource_layers'),
                       url(r'^datamanager/seed_SAR_DEM/$',
                           views.seed_SAR_DEM, name='seed_SAR_DEM'),
                       url(r'^datamanager/fhm_default_style/$',
                           views.fhm_default_style, name='fhm_default_style'),
                       url(r'^datamanager/rl_default_style/$',
                           views.rl_default_style, name='rl_default_style'),
                       url(r'^datamanager/sar_default_style/$',
                           views.sar_default_style, name='sar_default_style'),
                       url(r'^datamanager/dem_cov_default_style/$',
                           views.dem_cov_default_style, name='dem_cov_default_style'),
                       url(r'^datamanager/jurisdict__default_style/$',
                           views.jurisdict_default_style, name='jurisdict_default_style'),
                       url(r'^datamanager/list/$', views.file_list_geonode,
                           name='file_list_geonode'),
                       url(r'^datamanager/list/(?P<sort>[A-Za-z]+)/$',
                           views.file_list_geonode),
                       url(r'^datamanager/list/(?P<sort>[A-Za-z]+)/(?P<grid_ref>[-\w]+)/$',
                           views.file_list_geonode),
                       url(r'^datamanager/list_ceph/$',
                           views.file_list_ceph, name='file_list_ceph'),
                       url(
                           r'^datamanager/list_ceph/(?P<sort>[A-Za-z]+)/$', views.file_list_ceph),
                       )

# urlpatterns += automation_url

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls
import geonode.cephgeo.urls

from geonode.api.urls import api

import django_cas_ng

import autocomplete_light
from geonode.views import forbidden

#from geonode import settings

# Setup Django Admin
autocomplete_light.autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

                       # Static pages
                       url(r'^/?$', 'geonode.views.philgrid', name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

                       # EULA URLs
                       url(r'^eula/', include('geonode.eula.urls'), name='eula'),

                       # Permission denied handler
                       url(r'^forbidden/$', forbidden, name='forbidden'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # data.json
                       url(r'^data.json$', 'geonode.catalogue.views.data_json', name='data_json'),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       #(r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),
                       url(r'^register/$','geonode.datarequests.views.register', name='register'),

                       # Accounts
                       #url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/login$', 'django_cas_ng.views.login', name='account_ajax_login'),
                       url(r'^account/login/$','django_cas_ng.views.login', name='account_login'),
                       url(r'^account/login/$', 'django_cas_ng.views.login', name='cas_ng_login'),
                       url(r'^account/logout/$', 'django_cas_ng.views.logout', name='cas_ng_logout'),
                       url(r'^account/logout/$', 'django_cas_ng.views.logout', name='account_logout'),
                       url(r'^accounts/callback$', 'django_cas_ng.views.callback', name='cas_ng_proxy_callback'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

		       #Geocoding
                       (r'^geocoding/',include('geonode.arealocate.urls',namespace='arealocate')),

                       # Data Request Profiles
                       (r'^requests/', include('geonode.datarequests.urls', namespace='datarequests')),

                       # Misc
                       # url(r'^captcha/', include('captcha.urls')),

					   # CephGeo
					   url(r'^ceph/', include("geonode.cephgeo.urls")),

             # Automation
             url(r'^automation/', include('geonode.automation.urls', namespace='automation')),

					   #MapTiles
					   url(r'^maptiles/',include("geonode.maptiles.urls")),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),
                       (r'^services/', include('geonode.services.urls')),
                       url(r'', include(api.urls)),
                       (r'^api/', include('geonode.api.urls')),

                       # Reports views
                       (r'^reports/', include('geonode.reports.urls')),
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

if 'notification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^notifications/', include('notification.urls')),
                            )

if 'simple_sso.sso_server' in settings.INSTALLED_APPS:
    from simple_sso.sso_server.server import Server
    server = Server()
    urlpatterns += server.get_urls()

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

# Featured Maps Pattens
urlpatterns += patterns('',
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/$', 'geonode.maps.views.featured_map'),
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/info$', 'geonode.maps.views.featured_map_info'),
                        )

geonode/cephgeo/forms.py
from django import forms
from django.core.exceptions import ValidationError

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Button
from crispy_forms.bootstrap import FormActions

class DataInputForm(forms.Form):
    data = forms.CharField(widget=forms.Textarea(attrs={'style' : 'resize:none; width:100%; height:60%;', 'wrap' : 'virtual'}))
    update_grid = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Metadata output from bulk_upload.py:',
                'data',
                'update_grid',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )
        super(DataInputForm, self).__init__(*args, **kwargs)
        self.fields['update_grid'].initial  = True

class DataDeleteForm(forms.Form):
    data = forms.CharField(widget=forms.Textarea(attrs={'style' : 'resize:none; width:100%; height:60%;', 'wrap' : 'virtual'}))
    update_grid = forms.BooleanField(required=False)
    delete_from_ceph = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Metadata/object list for deletion',
                'data',
                'update_grid',
                'delete_from_ceph',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )
        super(DataDeleteForm, self).__init__(*args, **kwargs)
        self.fields['update_grid'].initial  = True
        self.fields['delete_from_ceph'].initial  = False


class RequestDataClassForm(forms.Form):
    LAZ = forms.BooleanField()
    DEM = forms.BooleanField()
    DSM = forms.BooleanField()
    DTM = forms.BooleanField()
    Orthophoto = forms.BooleanField()
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Choose which data to download :',
                'LAZ',
                'DEM',
                'DSM',
                'DTM',
                'Orthophoto',
            ),
            FormActions(
                Submit('submit', 'Create FTP Folder', css_class='button white'),
                Button('clear', 'Remove All Items', css_class='button white')
            )
        )
        super(RequestDataClassForm, self).__init__(*args, **kwargs)

geonode/cephgeo/templates/cart.html
{% extends "ceph_base.html" %}
{% load i18n %}

{% load staticfiles %}
{% load url from future %}

{% load eula_extras %}

{% block title %} {% trans "Cart" %} - {{ block.super }} {% endblock %}

{% block body_class %}Cephgeo cart{% endblock %}

{% block body_outer %}
  {% block body %}
  {% eula_modal_dialog "/ceph/ftp/" %} 

  <div class="page-header">
    <ul class="list-inline pull-right" id="sort">
      <li><a href="{% url 'maptiles_main' %}"><button class="btn btn-default">{% trans "Return to Selection" %}</button></a></li>
      {% if not cart.is_empty %}
        <li><button class="btn btn-default" data-toggle="modal" data-target="#eula-dialog">{% trans "Create FTP Folder" %}</a></li>
        <li><a href="{% url 'cephgeo.views.clear_cart' %}"><button class="btn btn-default">{% trans "Empty This Cart" %}</button></a></li>
      {% endif %}
    </ul>
  
  {% if not cartsize %}
    <h2 class="page-title">{% trans "Cart" %}</h2>
  {% else %}
    <h2 class="page-title">{% trans "Cart" %} [ {{ cartsize | filesizeformat }} ] </h2>
  {% endif %}
    
  </div>
  <div>
	<ul>
	  {% for message in messages %}
	    {% if 'error' in message.tags %}<li>{{ message }}</li>{% endif %}
	  {% endfor %}
	</ul>
  </div> 
  <ul class="list-inline pull-right" id="sort">
      <li>
          <label class="label-srs">SRS: </label>
          <select id="srsselection">
                {% for proj in projections %}
                    {% if proj == 'UTM 51N (Default)' %}
                        <option  id="{{ proj | slugify }}" 
                                 name="{{ proj | slugify }}" 
                                 value="default"
                                 selected="selected">
                    {% else %}             
                        <option  id="{{ proj | slugify }}" 
                                 name="{{ proj | slugify }}" 
                                 value="{{ proj | slugify }}">
                    {% endif %}
                        {{ proj }}
                      </option>
                 {% endfor %}
          </select>
      </li>
  </ul>
  <table id="cart_table" border="3" style="width:100% ">
        <tr >
            <th style="text-align: center;">Tile Object</th>
            <th style="text-align: center;">Size</th>
            <th style="text-align: center;">Quantity</th>
<!--
            <th style="text-align: center;"><i class="fa fa-minus-square"></i> {% trans "Remove" %} </th>
            <th>Total Price</th>
-->
        </tr>
        {% for item in cart %}
        <tr id="{{ item.product.name }}" name="{{ item.product.name }}" style="text-align: center;">
            <td>  {{ item.product.name }}</td>
            <td>  {{ item.product.size_in_bytes | filesizeformat }}</td>
            <td>  {{ item.quantity }}</td>
<!--
            <td width="100">
              <label class="cell-label-remove"><input type='checkbox' /></label>
            </td>
            <td>  {{ item.total_price }}</td>
-->
        </tr>
        {% endfor %}
    </table>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<style type="text/css">
	    tr.highlight {
		    background-color: #66CCFF;
		    color: #000;
		}
		.cell-label-remove {
			display: inline-block; 
			width: 100%;
		}
        .label-srs{
            font-size: 16px;
        }
	</style>
	<script type="text/javascript">
	    $('table[id="cart_table"] input[type=checkbox]').click(function () {
		    $(this).closest('tr').toggleClass("highlight", this.checked);
		});
        
        var activities = document.getElementById("srsselection");
        var eula_form = document.getElementById("form_eula")
        
        activities.addEventListener("change", function() {
            if(activities.value == "default")
            {
                //alert("Changing URL to /ceph/ftp/");
                eula_form.action = "/ceph/ftp/";
            }else{
                //alert("Changing URL to /ceph/ftp/" + activities.value + "/");
                eula_form.action = "/ceph/ftp/" + activities.value + "/";
            }
        });
	</script>
	    
{% endblock body %}
 {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/cephgeo/templates/ceph_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} File List {% endblock %}


{% block body_outer %}
  {% block body %}
  {% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/cephgeo/templates/ceph_manager.html
{% extends "ceph_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Ceph Data Management" %} {% endblock %}

{% block body_class %}Ceph Data Management{% endblock %}

{% block body_outer %}
{% block body %}
    <div class="page-header">
      <h2 class="page-title">Ceph Data Management</h2>
    </div>
    <div class="col-md-3">
        <div class="selections">
            <nav class="filter">
                <h4><a href="{% url 'geonode.cephgeo.views.file_list_geonode' %}" class="toggle toggle-nav"><i class="fa fa-files-o"></i>Datastore Files</a></h4>
                <h4><a href="{% url 'geonode.cephgeo.views.file_list_ceph' %}" class="toggle toggle-nav"><i class="fa fa-cubes"></i>Ceph Data Objects</a></h4>
                <h4><a href="{% url 'geonode.cephgeo.views.data_input' %}" class="toggle toggle-nav"><i class="fa fa-file-code-o"></i>Metadata Input</a></h4>
                <h4><a data-toggle="modal" data-target="#modal-metadata" href="" class="toggle toggle-nav"><i class="fa fa-file-text-o"></i>Metadata Update</a></h4>
                <h4><a data-toggle="modal" data-target="#modal-seed" href="" class="toggle toggle-nav"><i class="fa fa-leaf"></i>Seed Layers</a></h4>
                <h4><a data-toggle="modal" data-target="#modal-default-style" href="" class="toggle toggle-nav"><i class="fa fa-star-o"></i>Set Default Styles</a></h4>
                 <h4><a href="{% url 'automation:metadata_job' %}" class="toggle toggle-nav"><i class="fa fa-briefcase"></i>Automation</a></h4>
            </nav>
        </div>
    </div>


<div class="modal fade" id="modal-metadata" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">s
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">{% trans "Update metadata" %}</h4>
      </div>
      <form >
          <div class="modal-body" >
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="sample" value="fhm">
                Update Flood Hazard Map Metadata
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="sample" value="resourcelayer">
                Update Resource Layer Metadata
              </label>
            </div>
             <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="sample" value="sar">
                Update SAR DEM Metadata
              </label>
            </div>
           <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="sample" value="floodplain">
                Update FP/RB and SUC Keywoords
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="sample" value="lidar-cov">
                Update LiDAR Coverage
              </label>
            </div>

                          <!-- <div>
                <input type="radio" name="fhm" value="fhm">
                <label>Flood Hazard Map</label>
              </div>
              <div>
                <input type="radio" name="resourcelayer" value="resourcelayer">
                <label>Update Resource Layer Metadata</label>
              </div>
              <div>
                <input type="radio" name="sar" value="sar">
                <label>Update SAR DEM Metadata</label>
              </div> -->
          </div>
          <div class="modal-footer">
            <button id="update-metadata" class="btn btn-default" data-dismiss="modal">{% trans "Submit" %}</button>
          </div>
       </form>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-seed" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">{% trans "Seed Layers" %}</h4>
      </div>
      <form>
          <div class="modal-body">
              <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="seed"value="fhm">
                Seed Flood Hazard Map
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="seed"value="resourcelayer">
                Seed Resource Layer
              </label>
            </div>
             <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="seed" value="sar">
                Seed SAR DEM
              </label>
            </div>
              <!-- <div>
                <input type="radio" name="seed-fhm" value="seed-fhm">
                <label>Seed FHM Layers</label>
              </div>
              <div>
                <input type="radio" name="seed-resourcelayer" value="seed-resourcelayer">
                <label>Seed Resource Layers</label>
              </div>
              <div>
                <input type="radio" name="seed-sar" value="seed-sar">
                <label>Seed SAR DEM</label>
              </div> -->
          </div>
          <div class="modal-footer">
            <button id="seed-layers" class="btn btn-default" data-dismiss="modal">{% trans "Submit" %}</button>
          </div>
       </form>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-default-style" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">{% trans "Update Default Style of Layers" %}</h4>
      </div>
      <form>
          <div class="modal-body">
              <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="def-sld"value="fhm">
               Flood Hazard Map
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="def-sld"value="resourcelayer">
                Resource Layer
              </label>
            </div>
             <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="def-sld" value="sar">
                SAR DEM
              </label>
            </div>
             <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="def-sld" value="dem-cov">
                DEM Coverage
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="def-sld" value="jurisdict">
                Jurisdiction shapefiles
              </label>
            </div>
              <!-- <div>
                <input type="radio" name="fhm-def-sld" value="fhm-def-sld" id="fhm-def-sld">
                <label for="fhm">Flood Hazard Map</label>
              </div>
              <div>
                <input type="radio" name="rl-def-sld" value="rl-def-sld" id="rl-def-sld">
                <label for="resourcelayer">Resource Layer</label>
              </div>
              <div>
                <input type="radio" name="sar-def-sld" value="sar-def-sld" id="sar-def-sld">
                <label for="sar">Update SAR DEM</label>
              </div>
              <div>
                <input type="radio" name="dem-cov-def-sld" value="dem-cov-def-sld" id="dem-cov-def-sld">
                <label for="sar">DEM Coverage</label>
              </div>
              <div>
                <input type="radio" name="jurisdict-def-sld" value="jurisdict-def-sld" id="jurisdict-def-sld">
                <label for="sar">Jurisdiction shapefiles</label>
              </div> -->
          </div>
          <div class="modal-footer">
            <button id="assign-default-style" type="button" class="btn btn-default" data-dismiss="modal">{% trans "Submit" %}</button>
          </div>
       </form>
    </div>
  </div>
</div>



<!-- <div id="log"></div> -->

{% block extra_script %}

<script type="text/javascript">
$( "#update-metadata" ).click(function() {
    if ($( "input:checked" ).val() == "fhm"){
        // $( "#log" ).html( $( "input:checked" ).val() + " is checked!" );
            window.location = "{% url 'geonode.cephgeo.views.update_fhm_metadata' %}";
    }
    else if ($( "input:checked" ).val() == "resourcelayer"){
            window.location = "{% url 'geonode.cephgeo.views.update_pl2_metadata' %}";
    }
    else if ($( "input:checked" ).val() == "sar"){
            window.location = "{% url 'geonode.cephgeo.views.update_sar_metadata' %}";
    }
    else if ($( "input:checked" ).val() == "floodplain"){
            window.location = "{% url 'geonode.cephgeo.views.update_floodplain_keywords' %}";
    }
    else if ($( "input:checked" ).val() == "lidar-cov"){
            window.location = "{% url 'geonode.cephgeo.views.update_lidar_coverage' %}";
    }

});
</script>
<script type="text/javascript">
$( "#seed-layers" ).click(function() {
    if ($( "input:checked" ).val() == "fhm"){
        // $( "#log" ).html( $( "input:checked" ).val() + " is checked!" );
            window.location = "{% url 'geonode.cephgeo.views.seed_fhm_layers' %}";
    }
    else if ($( "input:checked" ).val() == "resourcelayer"){
            window.location = "{% url 'geonode.cephgeo.views.seed_resource_layers' %}";
    }
    else if ($( "input:checked" ).val() == "sar"){
            window.location = "{% url 'geonode.cephgeo.views.seed_SAR_DEM' %}";
    }

});
</script>
<script type="text/javascript">
$( "#assign-default-style" ).click(function() {
    if ($( "input:checked" ).val() == "fhm"){
            window.location = "{% url 'geonode.cephgeo.views.fhm_default_style' %}";
    }
    else if ($( "input:checked" ).val() == "resourcelayer"){
            window.location = "{% url 'geonode.cephgeo.views.rl_default_style' %}";
    }
    else if ($( "input:checked" ).val() == "sar"){
            window.location = "{% url 'geonode.cephgeo.views.sar_default_style' %}";
    }
    else if ($( "input:checked" ).val() == "dem-cov"){
            window.location = "{% url 'geonode.cephgeo.views.dem_cov_default_style' %}";
    }
     else if ($( "input:checked" ).val() == "jurisdict"){
            window.location = "{% url 'geonode.cephgeo.views.jurisdict_default_style' %}";
    }
});
</script>
{% endblock extra_script %}

{% endblock %}
 {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/cephgeo/templates/update_task.html
{% extends "ceph_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block body%}
<h1>{% trans "Update task is running in the background. You can check /var/log/celeryd.log for further details" %}</h1>

{% endblock %}